# render.yaml configuration for ShopEaslyAPP

services:
  - type: web
    name: ShopEaslyAPP
    env: node
    plan: free
    runtime: nodejs:20
    buildCommand: cd shopeasly-v11 && npm install
    start: cd shopeasly-v11 && node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    disk:
      sizeGB: 0.5
      mountPath: /data
      persistent: true
